# Methods on the abstract types `EmulatedInteger`/`EmulatedSigned`/`EmulatedUnsigned`. Loaded once at package precompile; each method serves every emulated type that ever gets created via `@emulate`. Compile-time constants come from the per-type `bits` and `storagetypeof` traits installed by the macro in `emulate.jl`.

# Unwrap to the storage value. The macro installs a `storagetypeof(::Type{T}) = <storage_type>` constant-returning method per emulated type, so this folds to a single `reinterpret`.
Base.getindex(x::EmulatedInteger) = reinterpret(x |> typeof |> storagetypeof, x)

# Value form returns a wider value (the unwrapped storage int); type form returns the storage type. Both routed through the per-type `storagetypeof` trait.
Base.widen(x::EmulatedInteger) = x[]
Base.widen(::Type{T}) where T<:EmulatedInteger = storagetypeof(T)

# Fallback constructor for any `Real`: route through `convert(storage, x)` (which throws `InexactError` for non-integer-valued floats/rationals or out-of-range integers), then funnel through the per-type checked `T(::storage_type)` constructor for the final range check. This single method also powers `convert(T, x)`, `round(T, x)`, `floor`/`ceil`/`trunc(T, x)` for any `Real x` — all of which funnel through `T(x)` in Base.
(::Type{T})(x::Real) where T<:EmulatedInteger = convert(storagetypeof(T), x) |> T
# Disambiguate against Base's `T(::BigFloat) where T<:Integer` and `T(::Rational) where T<:Integer`. Both bodies are the same forwarder as above.
for S in (BigFloat, Rational)
    @eval (::Type{T})(x::$S) where T<:EmulatedInteger = convert(storagetypeof(T), x) |> T
end

# `Base.tryparse_internal(::Type{T<:Integer}, ...)` accumulates digits in `T` itself, requiring `T(base)` to be representable. For narrow emulated types (e.g. `UInt3`, max 7) `T(10)` throws `InexactError` and parsing of any decimal string fails. Route through the storage type which always fits `base`, then range-check into `T`. `parse` reuses `T(::Real)`'s checked conversion (throws `InexactError` on overflow); `tryparse` does an explicit range check and returns `nothing` to honor its no-throw contract.
Base.parse(::Type{T}, s::AbstractString; base::Union{Integer,Nothing}=nothing) where T<:EmulatedInteger =
    convert(T, parse(storagetypeof(T), s; base))
function Base.tryparse(::Type{T}, s::AbstractString; base::Union{Integer,Nothing}=nothing) where T<:EmulatedInteger
    v = tryparse(storagetypeof(T), s; base)
    v === nothing && return nothing
    minvalue(T) <= v <= maxvalue(T) ? reinterpret(T, v) : nothing
end

# Bitwise `&`, `|`, `xor` of two clean operands stay clean for both signedness: wasted bits are either all-0 (unsigned) or a copy of bit N-1 (signed), and each op preserves that invariant — so `reinterpret` is safe and avoids the modular `% T` reduction.
for OP in (:&, :|, :xor)
    @eval Base.$OP(x::T, y::T) where T<:EmulatedInteger = reinterpret(T, $OP(x[], y[]))
end
# For signed types, `~` flips the sign bit and the wasted bits together, preserving the sign-extension invariant; no re-cleaning needed. Unsigned `~` flips the zero wasted bits to ones, so it routes through the modular reduction.
Base.:~(x::T) where T<:EmulatedSigned = reinterpret(T, ~x[])
Base.:~(x::T) where T<:EmulatedUnsigned = ~x[] % T

# `rem` effectively constructs an object `T` which is effectively `T(x % T)` in the most efficient way. This avoids the `InexactError` the default `T(x)` constructor would throw. It is heavily optimized with different methods for signed and unsigned types. This constructor is on the hot path of every arithmetic method generated by `@emulate`.
Base.rem(x::Integer, ::Type{T}) where T<:EmulatedSigned   = reinterpret(T, (convert(storagetypeof(T), x) << wastedbits(T)) >> wastedbits(T))
Base.rem(x::Integer, ::Type{T}) where T<:EmulatedUnsigned = reinterpret(T, convert(storagetypeof(T), x) & maxvalue(T))

# Two-operand `rem`/`mod`: Base's `Integer` fallback would try to promote and recurse forever (since `promote_rule(T, T) === T`). The result's magnitude is strictly less than `|y[]|`, which already fits in `T`, so the storage value already satisfies the wasted-bit invariant (unsigned: high bits zero; signed: sign-extended) and `reinterpret` is safe — and makes it visually obvious there is no recursion back into these same methods via `% T`.
Base.rem(x::T, y::T) where T<:EmulatedInteger = reinterpret(T, rem(x[], y[]))
Base.mod(x::T, y::T) where T<:EmulatedInteger = reinterpret(T, mod(x[], y[]))

# Type-traits derived from `bits` and `storagetypeof`, both of which are constant-returning single-method functions installed per emulated type by `@emulate`. Inference folds these chains down to the same literals the macro would have baked in directly.
wastedbits(::Type{T}) where T<:EmulatedInteger = 8*sizeof(T) - bits(T)
maxvalue(::Type{T})  where T<:EmulatedSigned   = storagetypeof(T)(-1) >>> (wastedbits(T) + 1)
maxvalue(::Type{T})  where T<:EmulatedUnsigned = ~storagetypeof(T)(0) >> wastedbits(T)
minvalue(::Type{T})  where T<:EmulatedSigned   = storagetypeof(T)(-1) << (bits(T) - 1)
minvalue(::Type{T})  where T<:EmulatedUnsigned = storagetypeof(T)(0)
hexdigits(::Type{T}) where T<:EmulatedInteger  = (((unsigned(bits(T)) + 3) >> 2) % Int)::Int

# Arithmetic methods break the otherwise infinite promotion fallback: every emulated type is a `primitive type`, not a `BitInteger` as `BitInteger` is a `Union` and therefore closed for extension. So Base's intrinsic-backed `op(::T, ::T) where T<:BitInteger` does not apply. The generic `op(::Integer, ::Integer) = op(promote(x, y)...)` would promote two same-typed emulated integers to themselves (per our `promote_rule`) and recurse — `StackOverflowError`. A concrete two-argument method per `EmulatedInteger` lowers the operation onto the storage type and routes the result through the modular `% T` reduction.
for OP in (:+, :-, :*)
    @eval Base.$OP(x::T, y::T) where T<:EmulatedInteger = $OP(x[], y[]) % T
end
# `div(x, y, R)` powers `div`/`fld`/`cld`/`fldmod`/`divrem` via Base's `RoundingMode`-dispatched routing. Base specializes the integer overloads per `RoundingMode` subtype (and separately for `T<:Unsigned`), so an abstract method on `EmulatedInteger` with an abstract `::RoundingMode` arg is ambiguous against `Base.div(::T, ::T, ::RoundingMode{:Down}) where T<:Unsigned` for `T<:EmulatedUnsigned`. Splitting by signedness and unrolling per `RoundingMode` makes our methods strictly more specific in every dimension Base specializes. The list is discovered once via `roundingmodetypes()` so a new mode added to Julia is picked up automatically.
roundingmodetypes() = unique(typeof(v) for v in (getfield(Base, n) for n in names(Base)) if v isa RoundingMode)
for RM in roundingmodetypes()
    for P in (EmulatedSigned, EmulatedUnsigned)
        @eval Base.div(x::T, y::T, r::$RM) where T<:$P = div(x[], y[], r) % T
    end
end
# `<<(::T,::Integer)` is installed per type by `@emulate` for the same reason: Base specializes shifts for `Unsigned` and for `Int` vs other `Integer`, so an abstract method is ambiguous.

Base.:-(x::T)   where T<:EmulatedInteger = -x[]  % T
# `abs` on an unsigned is the identity; `% T` would add a useless `& maxvalue` the compiler can't elide. Signed `abs` lowers to the storage intrinsic + modular re-clean.
Base.abs(x::EmulatedUnsigned) = x
Base.abs(x::T) where T<:EmulatedSigned = abs(x[]) % T

# Storage-level `-x[]` already produces the bit pattern of the flipped sign value (no overflow for non-`typemin` inputs and the same wraparound as 2's complement for `typemin`); the `% T` cast re-cleans the wasted bits.
Base.flipsign(x::T, y::Signed) where T<:EmulatedSigned = signbit(y) ? -x[] % T : x

# `c::Int` overload resolves a method-call ambiguity with Base's shift methods (which dispatch differently on `Int` vs. other `Integer`). For `c::Unsigned` we know the `>>` shift is non-negative: unsigned right-shift fills 0, signed arithmetic right-shift fills with the sign bit — both preserve the wasted-bit invariant, so `reinterpret` skips the modular reduction. The general `Integer`/`Int` paths must keep `% T` because a negative `c` turns into a left shift and dirties the wasted bits.
Base.:<<(x::T, c::Unsigned) where T<:EmulatedInteger = (x[] << c) % T
Base.:<<(x::T, c::Integer)  where T<:EmulatedInteger = (x[] << c) % T
Base.:<<(x::T, c::Int)      where T<:EmulatedInteger = (x[] << c) % T
Base.:>>(x::T, c::Unsigned) where T<:EmulatedInteger = reinterpret(T, x[] >> c)
Base.:>>(x::T, c::Integer)  where T<:EmulatedInteger = (x[] >> c) % T
Base.:>>(x::T, c::Int)      where T<:EmulatedInteger = (x[] >> c) % T

# Logical right shift: zero-extend first (`zext` masks the sign-extension on signed storage; no-op on unsigned), then plain shift on the storage value. The result has zeros in all bits at or above `bits(T)`, satisfying the unsigned invariant; for signed types `% T` then re-applies the (possibly negative) sign extension if bit `bits(T)-1` is set. The same three signatures as `>>` to break the same Base ambiguities.
Base.:>>>(x::T, c::Unsigned) where T<:EmulatedInteger = (zext(x) >>> c) % T
Base.:>>>(x::T, c::Integer)  where T<:EmulatedInteger = (zext(x) >>> c) % T
Base.:>>>(x::T, c::Int)      where T<:EmulatedInteger = (zext(x) >>> c) % T

# `Base.gcd`/`lcm` route through `checked_abs`. Unsigned: identity (no overflow possible since `abs` of a non-negative value is itself). Signed: throws `OverflowError` on `typemin(T)` (where `-typemin == typemin` would silently wrap in 2's complement), else plain `abs`.
Base.Checked.checked_abs(x::EmulatedUnsigned) = x
Base.Checked.checked_abs(x::T) where T<:EmulatedSigned =
    x == typemin(T) ? throw(OverflowError(lazy"checked arithmetic: cannot compute |x| for x = $x::$T")) : abs(x)

# `add_with_overflow` / `sub_with_overflow` / `mul_with_overflow` for emulated pairs: needed by `Base.Checked.checked_*` and `Base.lcm`. Each operator can have two problems: the storage operator may overflow (`overflow` flag), and the result may overflow into the wasted bits (`dirty` flag). The branches below are compile-time constants per `T` and fold to one of three regimes per call site.

# `rem` (`% T`) into an emulated type, paired with a flag saying whether the wasted bits were dirty. Returning the wrapped value alongside the flag lets the caller reuse the cast it had to compute anyway.
@inline rem_with_overflow(::Type{T}, x::Integer) where T<:EmulatedInteger =
    (r = x % T; (r, reinterpret(T |> storagetypeof, r) != x))

@inline function Base.Checked.add_with_overflow(x::T, y::T) where T<:EmulatedInteger
    if wastedbits(T) >= 1
        rem_with_overflow(T, x[] + y[])
    else
        s, overflow = Base.Checked.add_with_overflow(x[], y[])
        (reinterpret(T, s), overflow)
    end
end
@inline function Base.Checked.sub_with_overflow(x::T, y::T) where T<:EmulatedInteger
    if wastedbits(T) >= 1
        rem_with_overflow(T, x[] - y[])
    else
        s, overflow = Base.Checked.sub_with_overflow(x[], y[])
        (reinterpret(T, s), overflow)
    end
end
@inline function Base.Checked.mul_with_overflow(x::T, y::T) where T<:EmulatedInteger
    if wastedbits(T) >= bits(T)
        rem_with_overflow(T, x[] * y[])
    elseif wastedbits(T) >= 1
        s, overflow = Base.Checked.mul_with_overflow(x[], y[])
        r, dirty = rem_with_overflow(T, s)
        (r, overflow | dirty)
    else
        s, overflow = Base.Checked.mul_with_overflow(x[], y[])
        (reinterpret(T, s), overflow)
    end
end

# `minvalue`/`maxvalue` return literals of the storage type, so `reinterpret` suffices.
Base.typemin(::Type{T}) where T<:EmulatedInteger = reinterpret(T, minvalue(T))
Base.typemax(::Type{T}) where T<:EmulatedInteger = reinterpret(T, maxvalue(T))
Base.oneunit(::Type{T}) where T<:EmulatedInteger = reinterpret(T, T |> storagetypeof |> one)

# Storage has `wastedbits(T)` extra zero (unsigned) or sign-extension (signed) bits at the top; subtract them to get the logical leading-zero count.
Base.leading_zeros(x::T) where T<:EmulatedInteger = (leading_zeros(x[]) - wastedbits(T)) % Int

# Mask off the wasted high bits via `zext`, then count ones. Unsigned `zext` is a no-op; signed `zext` masks the sign-extension away, so a single uniform formula serves both.
Base.count_ones(x::EmulatedInteger) = count_ones(zext(x))
# Set the wasted high bits to 1 with an OR, then count zeros directly. Mirrors `count_ones`/`zext` but saves a subtraction; the mask folds to a literal (and is `0` for `bits == storagebits`, making the OR a no-op).
Base.count_zeros(x::T) where T<:EmulatedInteger = count_zeros(x[] | (~storagetypeof(T)(0) << bits(T)))

# Shift the wasted high bits out, then count leading ones in the storage type. Works for both signednesses because after the shift, the bits that count are the same as the logical high bits.
Base.leading_ones(x::T) where T<:EmulatedInteger = leading_ones(x[] << wastedbits(T)) % Int

# `x[] % UInt8` matches Base's two's-complement reinterpretation convention and lowers to a single `reinterpret`/truncation for any storage type.
Base.rem(x::EmulatedInteger, ::Type{UInt8}) = x[] % UInt8

Base.:/(x::T, y::T) where T<:EmulatedInteger = x[] / y[] # Should result in Float64

# Pad to the logical hex width, so `UInt3(7)` prints as `0x7` rather than `0x07`.
Base.show(io::IO, x::T) where T<:EmulatedUnsigned = print(io, "0x", string(x[], pad=hexdigits(T), base=16))
Base.show(io::IO, x::EmulatedSigned) = show(io, x[])

# Per Julia convention, `sign` returns a value of the same type as its argument. The storage-level `sign` produces 0/1/-1, all of which round-trip through `% T` cleanly. The edge case `Int1` (range `{-1, 0}`) is fine too: a 1-bit signed type can never hold a positive value, so `sign(x[])` is always `0` or `-1` — never `+1` — and no modular wrap-around happens.
Base.sign(x::T) where T<:EmulatedInteger = sign(x[]) % T
Base.signbit(x::EmulatedInteger) = x[] |> signbit

# Set the bit at position `bits(T)` so the trailing-zero search stops at the logical width; this matches Base's convention that `trailing_zeros(zero(T)) == 8*sizeof(T)`. The mask folds to a literal (`0` when `bits == storagebits`, in which case the OR is a no-op and Base's value already matches).
Base.trailing_zeros(x::T) where T<:EmulatedInteger = trailing_zeros(x[] | (one(storagetypeof(T)) << bits(T)))
# Mask the sign-extension away via `zext`, then count. Unsigned `zext` is a no-op; signed `zext` clears the high all-ones region that would otherwise inflate the count (e.g. for `-1` whose storage is all ones). Branchless, uniform with `count_ones`.
Base.trailing_ones(x::EmulatedInteger) = x |> zext |> trailing_ones

Base.AbstractFloat(x::EmulatedInteger) = x[] |> AbstractFloat

# Promote to the regular primitive types resulting in InexactErrors if values are not representable.
for B in Union{Base.BitInteger, Base.IEEEFloat} |> Base.uniontypes .|> Symbol
    @eval Base.$B(x::EmulatedInteger) = x[] |> $B
end

for f in (:<, :<=, :>, :>=)
    @eval Base.$f(x::EmulatedInteger, y::EmulatedInteger) = $f(x[], y[])
end

Base.hash(x::EmulatedInteger, h::UInt) = hash(x[], h)

# Pick the wider type; on equal width the unsigned wins; on equal width and equal signedness return `Base.Bottom` so the user can install their own rule for that pair. `bits(T)` and `bits(Y)` are constant-returning trait calls, so the body folds to a single `if` ladder per concrete `(T, Y)` pair. User overrides like `promote_rule(::Type{UInt3}, ::Type{MyInt}) = …` are strictly more specific than this abstract method on both arguments and win dispatch.
function Base.promote_rule(::Type{T}, ::Type{Y}) where {T<:EmulatedInteger, Y<:Integer}
    if bits(T) > bits(Y)
        T
    elseif bits(T) == bits(Y)
        if T <: Unsigned && Y <: Signed
            T
        elseif T <: Signed && Y <: Unsigned
            Y
        else
            Base.Bottom
        end
    else
        Y
    end
end

# Promote with `AbstractFloat`: mirrors Base's policy for primitive integers (e.g. `Int128 + Float16(1) === Inf16`) — the float wins regardless of width, and the user accepts whatever precision/overflow loss that implies (so e.g. `UInt1023 + Float16(1)` is allowed and likely returns `Inf16`). Base's float/integer promote rules use concrete `Float{16,32,64}` plus `Union{Bool,IntN,UIntN,...}` of concrete integer types, none of which include `EmulatedInteger`, so no ambiguity with Base.
Base.promote_rule(::Type{<:EmulatedInteger}, ::Type{F}) where F<:AbstractFloat = F

# `length` of a unit range of emulated values: Base's `AbstractUnitRange` fallback computes `last - first + one(T)` in the element type, which wraps silently when the count exceeds `typemax(T)` (e.g. `length(UInt3(0):UInt3(7))` would give `UInt3(0)`). Widen via `Int` on the storage values, mirroring what Base does for `UnitRange{<:Integer}` (returns `Int`).
Base.length(r::AbstractUnitRange{<:EmulatedInteger}) = max(0, Int(last(r)[]) - Int(first(r)[]) + 1)

# Uniform random sampling: draw a uniform storage value and re-clean via `% T`. Each logical value gets exactly `2^wastedbits(T)` storage preimages (one for each combination of the wasted bits), so the resulting distribution is uniform over `[minvalue(T), maxvalue(T)]` for both signed and unsigned types.
Base.rand(rng::Random.AbstractRNG, ::Random.SamplerType{T}) where T<:EmulatedInteger = rand(rng, storagetypeof(T)) % T

# Bit-rotation modulo the **logical** width `bits(T)`. Base's primitive `bitrotate` rotates within `8*sizeof`, which would shuffle wasted bits into the logical zone. Implemented branchlessly as `(z << k) | (z >>> (bits(T) - k))` on the zero-extended value, with `k = mod(k, bits(T))`. When `k == 0` the right-shift amount equals `bits(T)`: if `bits(T) < 8*sizeof(storage)` the high bits of `z` are zero so the shift yields 0; if `bits(T) == 8*sizeof(storage)` Julia defines the shift to yield 0 as well.
@inline function Base.bitrotate(x::T, k::Integer) where T<:EmulatedInteger
    k = mod(k, bits(T))
    z = zext(x)
    (z << k | z >>> (bits(T) - k)) % T
end

# Delegate to Base's optimized `bitstring` on the storage value, then keep only the logical low bits. Works for both signed and unsigned emulated integers because the storage is kept clean (sign-extended for negatives, zero-extended otherwise).
Base.bitstring(x::EmulatedInteger) = bitstring(x[])[end-bits(x)+1:end]
